# This environment variable tells terraform not to prompt for input.
export TF_INPUT = false

export TF_LOG ?=

export TF_VAR_namespace ?= krane

export TF_VAR_name ?= kube

export TF_VAR_cidr_block ?= 10.0.0.0/16

export TF_VAR_instance_type ?= t3.medium

export TF_VAR_health_check_type ?= EC2

export TF_VAR_wait_for_capacity_timeout ?= 10m

export TF_VAR_max_size ?= 5

export TF_VAR_min_size ?= 3

export TF_VAR_autoscaling_policies_enabled ?= true

export TF_VAR_cpu_utilization_high_threshold_percent ?= 80

export TF_VAR_cpu_utilization_low_threshold_percent ?= 20

export TF_VAR_associate_public_ip_address ?= true

export TF_VAR_kubernetes_version ?= 1.23

export TF_VAR_kubeconfig_path ?= ~/.kube/config

export TF_VAR_bootstrap_extra_args ?= --use-max-pods=40

export TF_VAR_ttl ?= 60
